<?php

/**
 * @file
 * Taxonomy localization main file.
 */

/**
 * Implements hook_views_api().
 */
function i18ntaxonomy_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_pre_render().
 */
function i18ntaxonomy_views_views_pre_render(&$view) {
  global $language;

  foreach($view->result as $delta => $term ){
    if(isset($term->tid)) {

      i18n_string_translate_langcode( $language->language );
      $localized_term = i18n_taxonomy_localize_terms( taxonomy_term_load( $term->tid ));
      $term->tid = $localized_term->tid;
      $term->taxonomy_term_data_name = $localized_term->name;
      $term->taxonomy_term_data_description = $localized_term->description;
    }
  }
}
